site_name: EmitYourParticles Documentation

theme:
  name: material
  logo: https://sxcu.net/6soaT2zBl.png
  favicon: https://sxcu.net/6speUAqA1.png
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.footer
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
    
nav:
  - 'index.md'
  - 'installation.md'
  - 'usage.md'

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - admonition
  - pymdownx.details